name: Release

on:
  push:
    tags:
      - "v*" # e.g. v0.2.0

permissions:
  contents: write # needed to create GitHub Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { goos: linux, goarch: amd64, ext: "" }
          - { goos: linux, goarch: arm64, ext: "" }
          - { goos: darwin, goarch: amd64, ext: "" }
          - { goos: darwin, goarch: arm64, ext: "" }
          - { goos: windows, goarch: amd64, ext: ".exe" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          set -euo pipefail
          VER="${GITHUB_REF_NAME#v}"
          OUT="justify-${GOOS}-${GOARCH}${{ matrix.ext }}"
          mkdir -p dist
          CGO_ENABLED=0 go build -trimpath -ldflags "-s -w -X main.version=${VER}" -o "dist/${OUT}" .

      - name: Checksums
        run: |
          set -euo pipefail
          cd dist
          sha256sum * > checksums.txt
          cat checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
