name: Release

on:
  push:
    tags: ["v*"] # e.g. v0.3.0

permissions:
  contents: write # needed to create/update releases

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { goos: linux, goarch: amd64, ext: "" }
          - { goos: linux, goarch: arm64, ext: "" }
          - { goos: darwin, goarch: amd64, ext: "" }
          - { goos: darwin, goarch: arm64, ext: "" }
          - { goos: windows, goarch: amd64, ext: ".exe" }
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          set -euo pipefail
          VER="${GITHUB_REF_NAME#v}"
          MOD=$(go list -m -f '{{.Path}}')
          BIN="justify-${GOOS}-${GOARCH}${{ matrix.ext }}"
          mkdir -p dist
          CGO_ENABLED=0 go build -trimpath -ldflags "-s -w -X ${MOD}/justify.Version=${VER}" -o "dist/${BIN}" .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: justify-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*
          if-no-files-found: error
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Generate checksums
        run: |
          set -euo pipefail
          cd dist
          sha256sum * > checksums.txt
          cat checksums.txt

      - name: Create / Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
